[build]
  command = "npm run build:all"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  TZ = "America/Chicago"

[[headers]]
  for = "/data/*"
  [headers.values]
  Cache-Control = "no-store"

[[headers]]
  for = "/blog/*"
  [headers.values]
  Cache-Control = "no-store"

[[headers]]
  for = "/daily/*"
  [headers.values]
  Cache-Control = "no-store"

[functions]
  node_bundler = "esbuild"

[[scheduled.functions]]
  name = "send-devotional"
  schedule = "0 13 * * *"
  # Runs every day at 13:00 UTC (≈ 8:00 AM America/Chicago)
  # Adjust if you want a different time
