[build]
  command = "npm run build:all"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  TZ = "America/Chicago"

[[headers]]
  for = "/data/*"
  [headers.values]
  Cache-Control = "no-store"

[[headers]]
  for = "/daily/*"
  [headers.values]
  Cache-Control = "no-store"

[[headers]]
  for = "/blog/*"
  [headers.values]
  Cache-Control = "no-store"
