name: Daily Publish
on:
  schedule:
    - cron: "0 11 * * *"   # ~6:00 AM America/Chicago during CDT
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (if any)
        run: npm ci || true

      - name: Build daily pages & data
        run: npm run build:daily

      - name: Publish to Netlify (force prod publish)
        run: npx netlify-cli deploy --dir . --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
